#version 450

#extension GL_ARB_separate_shader_objects : enable
#extension GL_ARB_shading_language_420pack : enable
#extension GL_EXT_nonuniform_qualifier : enable
#extension GL_EXT_shader_image_load_formatted : enable

#define GCT_USE_IMAGE_POOL_WITHOUT_FORMAT

layout(local_size_x = 16, local_size_y = 8 ) in;

#include <gct/constants.h>
#include <gct/global_uniforms.h>
#include <gct/scene_graph/image_pool.h>
#include <gct/scene_graph/texture_pool.h>
#include <gct/scene_graph/matrix_pool.h>
#include <gct/scene_graph/instance_resource_index.h>
#include <gct/scene_graph/visibility_pool.h>
#include <gct/scene_graph/k+buffer.h>
#include <gct/scene_graph/read_primitive.h>

layout(push_constant) uniform PushConstants {
  uint gbuffer_format;
  uint gbuffer;
  uint position;
  uint depth;
} push_constants;

void main()  {
  const ivec2 screen_pos = ivec2( gl_GlobalInvocationID.xy );

  kplus_iter iter = kplus_begin(
    kplus_image( push_constants.gbuffer, push_constants.position ),
    screen_pos,
    push_constants.gbuffer_format
  );

  float nearest_depth = 1.0;
  kplus_iter nearest_opaque = iter;
  for( uint i = 0u; i != 4u; ++i ) {
    if( kplus_is_end( iter ) ) {
      break;
    }
    vec4 albedo = kplus_get_albedo( iter );
    if( albedo.w != 0.0f ) {
      nearest_depth = kplus_get_depth( iter );
    }
    if( albedo.w == 1.0f ) {
      nearest_opaque = iter;
    }
    else if( albedo.w == 0.0f ) {
      kplus_erase( iter );
    }
    iter = kplus_next( iter );
  }
  kplus_erase_back( nearest_opaque );
  imageStore( image_pool_2d[ nonuniformEXT( push_constants.depth ) ], screen_pos, vec4( nearest_depth, 0.0, 0.0, 0.0 ) );
  
}

