#version 450

#extension GL_ARB_separate_shader_objects : enable
#extension GL_ARB_shading_language_420pack : enable
#extension GL_EXT_nonuniform_qualifier : enable
#extension GL_EXT_shader_image_load_formatted : enable

// 8bit、16bitの値のバッファを読めるようにする拡張を使う
// 頂点バッファをシェーダーから読むのに使う
#extension GL_EXT_shader_16bit_storage : enable
#extension GL_EXT_shader_8bit_storage : enable

// Subgroup演算を使う
#extension GL_KHR_shader_subgroup : enable
#extension GL_KHR_shader_subgroup_arithmetic : enable
#extension GL_KHR_shader_subgroup_ballot : enable
#extension GL_KHR_shader_subgroup_vote : enable

// 64bit整数を使う
#extension GL_ARB_gpu_shader_int64 : enable

layout(local_size_x = 16, local_size_y = 8 ) in;

#define GCT_SHADER_SCENE_GRAPH_DISABLE_PUSH_CONSTANT
#define GCT_ENABLE_8BIT_16BIT_STORAGE
#define GCT_USE_IMAGE_POOL_WITHOUT_FORMAT
#include <gct/constants.h>
#include <gct/global_uniforms.h>
#include <gct/scene_graph/image_pool.h>
#include <gct/scene_graph/texture_pool.h>
#include <gct/scene_graph/matrix_pool.h>
#include <gct/scene_graph/instance_resource_index.h>
#include <gct/scene_graph/visibility_pool.h>
#include <gct/scene_graph/k+buffer.h>
#include <gct/scene_graph/read_primitive.h>
#include <gct/scene_graph/accessor.h>
#include <gct/global_uniforms.h>
#include <gct/rasterize.h>

layout(push_constant) uniform PushConstants {
  uint gbuffer_format;
  uint gbuffer;
  uint position;
  uint depth;
} push_constants;

void main()  {
  const ivec2 screen_pos = ivec2( gl_GlobalInvocationID.xy );

  kplus_iter iter = kplus_begin(
    kplus_image( push_constants.gbuffer, push_constants.position ),
    screen_pos,
    push_constants.gbuffer_format
  );
  /*const float alpha = kplus_get_albedo( iter ).w;
  if( alpha != 0.0f ) {
    return;
  }*/
  vec4 id_cache[ 4 ] = vec4[4](
    vec4( 0, 0, 0, 0 ),
    vec4( 0, 0, 0, 0 ),
    vec4( 0, 0, 0, 0 ),
    vec4( 0, 0, 0, 0 )
  );
  vec4 texcoord_cache[ 4 ] = vec4[4](
    vec4( 0, 0, 0, 0 ),
    vec4( 0, 0, 0, 0 ),
    vec4( 0, 0, 0, 0 ),
    vec4( 0, 0, 0, 0 )
  );
  vec4 albedo_cache[ 4 ] = vec4[4](
    vec4( 0, 0, 0, 0 ),
    vec4( 0, 0, 0, 0 ),
    vec4( 0, 0, 0, 0 ),
    vec4( 0, 0, 0, 0 )
  );
  face_texcoord face_texcoord_cache[ 4 ];
  vec2 st_cache[ 4 ] = vec2[4](
    vec2( 0, 0 ),
    vec2( 0, 0 ),
    vec2( 0, 0 ),
    vec2( 0, 0 )
  );

  kplus_iter nearest_opaque = iter;
  for( uint i = 0u; i != 4u; ++i ) {
    if( kplus_is_end( iter ) ) {
      break;
    }

    vec2 st;
    float lod;
    vec4 id;
    kplus_get_st_lod_id( iter, st, lod, id );
    const primitive_resource_index_type prim = primitive_resource_index[ uint( id.y ) ];
    const face_texcoord f = read_face_texcoord( prim.mesh, uint( id.w ) );
    const vec2 texcoord = rasterization_interpolate( st, f.texcoord[ 0 ], f.texcoord[ 1 ], f.texcoord[ 2 ] );
    vec4 albedo = read_primitive_albedo_only(
      uint( id.y ),
      vec3( texcoord, lod )
    );
    
    id_cache[ iter.layer ] = id;
    texcoord_cache[ iter.layer ] = vec4( texcoord, lod, 0.0 );
    albedo_cache[ iter.layer ] = albedo;
    face_texcoord_cache[ iter.layer ] = f;
    st_cache[ iter.layer ] = st;

    if( albedo.w >= 1.0f ) {
      nearest_opaque = iter;
      iter = kplus_next( iter );
    }
    else if( albedo.w <= 0.0f ) {
      kplus_erase( iter );
    }
    else {
      iter = kplus_next( iter );
    }
  }
  kplus_erase_back( nearest_opaque );

  iter = nearest_opaque;

  kplus_iter nearest_iter = iter;
  for( uint i = 0u; i != 4u; ++i ) {
    if( kplus_is_end( iter ) ) {
      break;
    }
    const vec4 id = id_cache[ iter.layer ];
    nearest_iter = iter;
    if( id.z != -1 ) {
      const vec3 texcoord = texcoord_cache[ iter.layer ].xyz;
      const primitive_resource_index_type prim = primitive_resource_index[ uint( id.y ) ];
      const face_attribute fa = read_face_attribute_without_texcoord( prim.mesh, face_texcoord_cache[ iter.layer ] );
      const vec2 st = st_cache[ iter.layer ];
      const vec4 normal = rasterization_interpolate( st, fa.vertex[ 0 ].normal, fa.vertex[ 1 ].normal, fa.vertex[ 2 ].normal );
      const vec4 tangent = rasterization_interpolate( st, fa.vertex[ 0 ].tangent, fa.vertex[ 1 ].tangent, fa.vertex[ 2 ].tangent );
     
      primitive_value p = read_primitive_excluding_albedo(
        uint( id.y ),
        vec4( 0, 0, 0, 0 ),
        normal.xyz,
        tangent,
        texcoord_cache[ iter.layer ].xyz,
        vec4( 0.0f, 0.0f, 0.0f, 0.0f ),
        vec4( 0.0f, 0.0f, 0.0f, 0.0f ),
        albedo_cache[ iter.layer ]
      );
      kplus_insert_complement( iter, p, id );
    }
    const uint visibility_index = instance_resource_index[ uint( id.x ) ].visibility;
    visibility_pool[ visibility_index ] = 1;
    iter = kplus_next( iter );
  }
  float nearest_depth = kplus_get_depth( nearest_iter );
  imageStore( image_pool_2d[ nonuniformEXT( push_constants.depth ) ], screen_pos, vec4( nearest_depth, 0.0, 0.0, 0.0 ) );
  
}

