#ifndef GCT_SHADER_TOPOLOGY_ID_H
#define GCT_SHADER_TOPOLOGY_ID_H

#define GCT_SHADER_TOPOLOGY_ID_POINT 0
#define GCT_SHADER_TOPOLOGY_ID_LINE 1
#define GCT_SHADER_TOPOLOGY_ID_TRIANGLE 2
#define GCT_SHADER_TOPOLOGY_ID_DGF 3

#endif


