#ifndef GCT_SHADER_TYPE_ID_H
#define GCT_SHADER_TYPE_ID_H

#define GCT_SHADER_TYPE_ID_FLOAT 0
#define GCT_SHADER_TYPE_ID_I8 1
#define GCT_SHADER_TYPE_ID_U8 2
#define GCT_SHADER_TYPE_ID_I16 3
#define GCT_SHADER_TYPE_ID_U16 4
#define GCT_SHADER_TYPE_ID_U32 5

#endif

