#ifndef GCT_SHADER_TYPE_ID_H
#define GCT_SHADER_TYPE_ID_H

#define GCT_SHADER_TYPE_ID_FLOAT 0
#define GCT_SHADER_TYPE_ID_I8 1
#define GCT_SHADER_TYPE_ID_U8 2
#define GCT_SHADER_TYPE_ID_I16 3
#define GCT_SHADER_TYPE_ID_U16 4
#define GCT_SHADER_TYPE_ID_U32 5

#define GCT_SHADER_TYPE_ID_HALF 128
#define GCT_SHADER_TYPE_ID_FIXED 129
#define GCT_SHADER_TYPE_ID_DGF 130
#define GCT_SHADER_TYPE_ID_N21T11 131
#define GCT_SHADER_TYPE_ID_N31 132

#endif

