if( NOT DGFSDK_ROOT )
  find_path (DGFSDK_INCLUDE_DIRS NAMES DGF.h PATHS /usr/include /usr/local/include )
  find_library (DGFSDK_DGFLIB_LIBRARY NAMES DGFLib )
  find_library (DGFSDK_DGFBAKER_LIBRARY NAMES DGFBaker )
else()
  find_path (DGFSDK_INCLUDE_DIRS NAMES DGF.h PATHS ${DGFSDK_ROOT}/include )
  find_library (DGFSDK_DGFLIB_LIBRARY NAMES DGFLib PATHS ${DGFSDK_ROOT}/lib ${DGFSDK_ROOT}/lib64 ${DGFSDK_ROOT} NO_DEFAULT_PATH )
  find_library (DGFSDK_DGFBAKER_LIBRARY NAMES DGFBaker PATHS ${DGFSDK_ROOT}/lib ${DGFSDK_ROOT}/lib64 ${DGFSDK_ROOT} NO_DEFAULT_PATH )
endif()

if( DGFSDK_DGFLIB_LIBRARY AND DGFSDK_DGFBAKER_LIBRARY )
  set( DGFSDK_LIBRARIES ${DGFSDK_DGFLIB_LIBRARY};${DGFSDK_DGFBAKER_LIBRARY} )
endif()

include (FindPackageHandleStandardArgs)
find_package_handle_standard_args(
  DGFSDK DEFAULT_MSG
  DGFSDK_INCLUDE_DIRS DGFSDK_LIBRARIES
)
mark_as_advanced(DGFSDK_INCLUDE_DIRS DGFSDK_LIBRARIES)

